# Generated by Django 3.2.3 on 2021-06-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Images')),
                ('class_name', models.TextField(max_length=30)),
                ('teacher', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.TextField(max_length=30, unique=True)),
                ('name', models.TextField(default='student_name', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='teacher', max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.student')),
                ('name', models.TextField(default='student_name', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.TextField(max_length=40, null=True)),
                ('subject_code', models.TextField(max_length=40)),
                ('image', models.ImageField(null=True, upload_to='Images')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.TextField(default='absent', max_length=30, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
