# Generated by Django 3.2.2 on 2021-07-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
