# Generated by Django 3.2.2 on 2021-07-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_info',
            name='branch',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='academic_info',
            name='semester',
            field=models.CharField(max_length=20),
        ),
    ]
