# Generated by Django 3.2.2 on 2021-07-03 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.TextField(max_length=8)),
                ('branch', models.TextField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='attendance_file',
            field=models.FileField(default='records/somefile1.xlsx', null=True, upload_to='records'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.TextField(default='no designation', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(default='user name', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.academic_info'),
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.academic_info'),
        ),
    ]
