# Generated by Django 3.2.2 on 2021-07-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_info',
            name='scheme',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='academic_info',
            name='semester',
            field=models.TextField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
