# Generated by Django 3.2.2 on 2021-07-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210708_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_table',
            name='subject',
        ),
        migrations.AddField(
            model_name='class',
            name='image1',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
        migrations.AddField(
            model_name='class',
            name='image2',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
    ]
