# Generated by Django 3.2.2 on 2021-06-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_teacher_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='designation',
        ),
    ]
