# Generated by Django 3.2.2 on 2021-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_table',
            name='time',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
