# Generated by Django 3.2.3 on 2021-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_class_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
        migrations.AddField(
            model_name='class',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
