# Generated by Django 3.2.2 on 2021-07-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210707_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
        migrations.AlterField(
            model_name='academic_info',
            name='branch',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='academic_info',
            name='semester',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attend',
            field=models.CharField(default='absent', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='name',
            field=models.CharField(default='student_name', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='student_name', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='no designation', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='student', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user name', max_length=40, null=True),
        ),
    ]
