# Generated by Django 3.2.2 on 2021-07-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210708_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_table',
            name='subject',
        ),
    ]
