# Generated by Django 3.2.3 on 2021-06-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210602_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='class',
            name='time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
