# Generated by Django 3.2.2 on 2021-07-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210707_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.TextField(max_length=40, unique=True),
        ),
    ]
