# Generated by Django 3.2.2 on 2021-07-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_info',
            name='branch',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academic_info',
            name='semester',
            field=models.TextField(max_length=8, null=True),
        ),
    ]
