# Generated by Django 3.2.3 on 2021-06-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210602_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.TextField(max_length=40, null=True)),
                ('subject_code', models.TextField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject_code',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
    ]
