# Generated by Django 3.2.2 on 2021-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(default='user name', max_length=40, null=True),
        ),
    ]
