# Generated by Django 3.2.2 on 2021-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='attendance_file',
            field=models.FileField(null=True, upload_to='records'),
        ),
    ]
