# Generated by Django 3.2.2 on 2021-07-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_subject_attendance_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='attendance_file',
            field=models.FileField(default='records/somefile1.xlsx', null=True, upload_to='records'),
        ),
    ]
