# Generated by Django 3.2.2 on 2021-07-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_subject_attendance_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Class_Session',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='Class',
            new_name='Class_session',
        ),
    ]
