# Generated by Django 3.2.2 on 2021-07-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210703_0110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class_Session',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='Class_session',
            new_name='Class',
        ),
    ]
