# Generated by Django 3.2.2 on 2021-07-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210703_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.TextField(max_length=30, unique=True)),
                ('branch', models.TextField(max_length=30, unique=True)),
            ],
        ),
    ]
