# Generated by Django 3.2.2 on 2021-07-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210703_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_info',
            name='branch',
            field=models.TextField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='academic_info',
            name='semester',
            field=models.TextField(max_length=8),
        ),
    ]
