# Generated by Django 3.2.2 on 2021-07-03 17:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210703_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='attendance_file',
            field=models.FileField(null=True, upload_to=api.models.path_and_rename),
        ),
    ]
